Loaded data columns:  Index(['AATK_rna', 'ABHD14A_rna', 'ABHD3_rna', 'ABHD5_rna', 'ABL2_rna',
       'ABO_rna', 'ACAD8_rna', 'ACADL_rna', 'ACHE_rna', 'ACOT6_rna',
       ...
       'ZNF600_rna', 'ZNF652_rna', 'ZNF77_rna', 'ZNF79_rna', 'ZNF8_rna',
       'ZNFX1_rna', 'ZNRF1_rna', 'ZPBP_rna', 'ZSWIM7_rna', 'ZYG11A_rna'],
      dtype='object', length=1082)
Number of features: 50 | Cross-validated C-index: 0.8565 ± 0.0561
Number of features: 100 | Cross-validated C-index: 0.8820 ± 0.0510
Number of features: 150 | Cross-validated C-index: 0.8857 ± 0.0462
Number of features: 200 | Cross-validated C-index: 0.9106 ± 0.0480
Number of features: 250 | Cross-validated C-index: 0.9106 ± 0.0502
Number of features: 300 | Cross-validated C-index: 0.8461 ± 0.0919
No improvement since 0.9154166666666665 for the last 272 iterations. Early stopping...

Best results with 198 features: C-index 0.9154 ± 0.0389
Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 69, in <module>
    removed_df.to_excel(writer, sheet_name="Filtering")
NameError: name 'removed_df' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 68, in <module>
    with pd.ExcelWriter(os.path.join(args.results_dir, f'fs_{args.target_data}.xlsx')) as writer:
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1476, in __exit__
    self.close()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1480, in close
    self._save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 109, in _save
    self.book.save(self._handles.handle)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/workbook.py", line 386, in save
    save_workbook(self, filename)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 294, in save_workbook
    writer.save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 275, in save
    self.write_data()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 89, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 150, in write
    self.write_views()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 137, in write_views
    active = get_active_sheet(self.wb)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 35, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible
Loaded data columns:  Index(['AATBC_rna', 'ABCA10_rna', 'ABCA3_rna', 'ABCD1_rna', 'ABHD1_rna',
       'ABHD12B_rna', 'ABHD16B_rna', 'ABHD17A_rna', 'ABHD17B_rna', 'ABHD3_rna',
       ...
       'ZNF586_rna', 'ZNF662_rna', 'ZNF671_rna', 'ZNF672_rna', 'ZNF71_rna',
       'ZNF76_rna', 'ZNF77_rna', 'ZNF79_rna', 'ZNF836_rna', 'ZSWIM7_rna'],
      dtype='object', length=1103)
Number of features: 50 | Cross-validated C-index: 0.8903 ± 0.0771
Number of features: 100 | Cross-validated C-index: 0.9492 ± 0.0511
Number of features: 150 | Cross-validated C-index: 0.9119 ± 0.0513
Number of features: 200 | Cross-validated C-index: 0.9073 ± 0.0502
Number of features: 250 | Cross-validated C-index: 0.8957 ± 0.0500
Number of features: 300 | Cross-validated C-index: 0.9308 ± 0.0319
No improvement since 0.9542759972895339 for the last 275 iterations. Early stopping...

Best results with 96 features: C-index 0.9543 ± 0.0503
Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 69, in <module>
    removed_df.to_excel(writer, sheet_name="Filtering")
NameError: name 'removed_df' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 68, in <module>
    with pd.ExcelWriter(os.path.join(args.results_dir, f'fs_{args.target_data}.xlsx')) as writer:
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1476, in __exit__
    self.close()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1480, in close
    self._save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 109, in _save
    self.book.save(self._handles.handle)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/workbook.py", line 386, in save
    save_workbook(self, filename)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 294, in save_workbook
    writer.save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 275, in save
    self.write_data()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 89, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 150, in write
    self.write_views()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 137, in write_views
    active = get_active_sheet(self.wb)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 35, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible
Loaded data columns:  Index(['AA_rna', 'AADAC_rna', 'ABCB9_rna', 'ABCC6P2_rna', 'ABI1_rna',
       'ACAD11_rna', 'ACADS_rna', 'ACCPN_rna', 'ACOX3_rna', 'ACP6_rna',
       ...
       'ZNF174_rna', 'ZNF204P_rna', 'ZNF277_rna', 'ZNF354C_rna', 'ZNF451_rna',
       'ZNF521_rna', 'ZNF597_rna', 'ZNF76_rna', 'ZP1_rna', 'ZWILCH_rna'],
      dtype='object', length=726)
Number of features: 50 | Cross-validated C-index: 0.6574 ± 0.0377
Number of features: 100 | Cross-validated C-index: 0.6829 ± 0.0479
Number of features: 150 | Cross-validated C-index: 0.7032 ± 0.0640
Number of features: 200 | Cross-validated C-index: 0.6813 ± 0.0552
Number of features: 250 | Cross-validated C-index: 0.7133 ± 0.0642
Number of features: 300 | Cross-validated C-index: 0.7260 ± 0.0631
No improvement since 0.7298135724265975 for the last 264 iterations. Early stopping...

Best results with 270 features: C-index 0.7298 ± 0.0615
Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 69, in <module>
    removed_df.to_excel(writer, sheet_name="Filtering")
NameError: name 'removed_df' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/nfs/Desktop/OViTANet/fs.py", line 68, in <module>
    with pd.ExcelWriter(os.path.join(args.results_dir, f'fs_{args.target_data}.xlsx')) as writer:
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1476, in __exit__
    self.close()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1480, in close
    self._save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 109, in _save
    self.book.save(self._handles.handle)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/workbook.py", line 386, in save
    save_workbook(self, filename)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 294, in save_workbook
    writer.save()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 275, in save
    self.write_data()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/writer/excel.py", line 89, in write_data
    archive.writestr(ARC_WORKBOOK, writer.write())
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 150, in write
    self.write_views()
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 137, in write_views
    active = get_active_sheet(self.wb)
  File "/home/ezgitwo/miniconda3/envs/surv/lib/python3.10/site-packages/openpyxl/workbook/_writer.py", line 35, in get_active_sheet
    raise IndexError("At least one sheet must be visible")
IndexError: At least one sheet must be visible
